import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Link from "next/link";
import Image from "next/image";

function Navbar() {
  return (
    <nav style={{ width: "100%", padding: "16px 0", backgroundColor: "#f8f9fa",borderBottom: "1px solid #eee", display: "flex", alignItems: "center", justifyContent: "space-between" }}>
      <div style={{ display: "flex", alignItems: "center" }}>
        <Link href="/">
          <Image src="/Aneo-logo.png" alt="Aneo Logo" width={120} height={40} style={{ cursor: "pointer" }} />
        </Link>
      </div>
      <div style={{ display: "flex", alignItems: "center" }}>
        <Link href="/login">
          <button style={{ marginRight: 12, cursor: "pointer", color: "#333" }}>Login</button>
        </Link>
        <Link href="/register">
          <button style={{ cursor: "pointer", color: "#333" }}>Register</button>
        </Link>
      </div>
    </nav>
  );
}

function Footer() {
  return (
    <footer style={{ width: "100%", padding: "16px 0", borderTop: "1px solid #eee", textAlign: "center", marginTop: "auto" }}>
      <span style={{ color: "#888" }}>© {new Date().getFullYear()} Aneo. All rights reserved.</span>
    </footer>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{ minHeight: "100vh", display: "flex", flexDirection: "column" }}
      >
        <Navbar />
        <div style={{ flex: 1, width: "100%" }}>{children}</div>
        <Footer />
      </body>
    </html>
  );
}
